### ISSUE TITLE
take more control of alignments

### ISSUE THREAD

**Issue by roblanf** [roblanf/gap_trees#3]
@duchene, this is just an idea, let me know what you think in this thread.

So, the problem I see is that we simulate alignments that have an expected branch length of e.g. 0.001. But that's not necessarily what we get, because it's a stochastic simulation.

The problem here is that this will make it hard to distinguish signal from noise. E.g. imagine that we find with an internal branch length of 0.001 and 80% gaps, we get the wrong tree 10% of the time. 

A branch length of 0.001 and an alignment of 1000 can manifest itself in a few ways:

1. 0 substitutions
2. 1 substituiton
3. 2 substitutions
(let's ignore the rare cases with >2)

And for each substitution, it will either appear in a position with gaps, or outside it. 

It would be nice to control these things as part of the simulation. Or at least to measure them post-hoc.

Either way, the important thing for now is that we KNOW there are huge issues with monotypic alignments, so what we should be interested in when the internal branch length is non-zero is everything EXCEPT monotypic alignments.

A simple way to do this would be when we simulate the initial alignment, we just make sure that it has exactly the number of expected substitutions. E.g. for a brlen of 0.001 we could ensure that there's exactly 1 substitution. If we did this up to and including branch lengths of 0.01, I think we'd be on safe ground. After that, we could just have a check for monotypic alignments and exclude them.

A simpler approach would be to just always exclude monotypic alignments. Then we just have to be aware that our expected branchlength for the lower end of the branch length spectrum will be biased upwards a little.

Thoughts?

**Comment by duchene** [comment]
So, to recap from our conversation yesterday. We can either (i) measure the number of substitutions in each simulation, or (ii) use a while loop to only save the results of simulations with at least one variable site.

Both of these have issues: (i) might contain too few non-monotipic alignments in some cases, so that the comparison among scenarios becomes unfair, and (ii) will lead to a skewed distribution under the simulation scenario.

I think we can just code them both, which should be easy, and toggle between them if needed. Perhaps I will begin focusing on (i) because it seems easier.

**Comment by roblanf** [comment]
I think recording the number of subs. is a good idea to start.

Specifically, there are the following possible site patterns for a sub on the internal branch (we can start there, and record other subs later if we really want to):
```
t1   A-A-
t2   AAAA
t3   CC--
t4   CCCC
```

I.e. the gaps can either be absent, non-homologus (two options), or homologous.

If you record those as four extra variables to put in the results, that would be ideal I think. Then we can just count them up.

**Comment by roblanf** [comment]
And for the while loop, I don't think it would be that hard. 

All we need is a function like

```
is_monotypic(alignment)
```

that returns `TRUE` if it is (or if no alignment is passed), and `FALSE` if it isn't. This is easy I think there must be existing functions that count the number of variable sites (alternatively we can just test whether the strings for all spp in the alignment are exactly identical).

Then we can do:

```
while(is_monotypic(alignment)):
    alignment = generate_alignment(...)
```

Then once this is done, we put the gaps into the alignment.

**Comment by duchene** [comment]
I have updated runIQtree.R to produce a vector with the output as discussed. 

I am in the process of updating run.4tip.gaps to allow us to force non-monotypic alignments. 

I also created a new version of the analysis_200719.Rscript which I think streamlines things. If you agree with these changes we can make that the working version (now I think about it, a git branch might've been good).

The plotting code in the analysis script still needs to be checked or redone.

The standard bootstrap is fairly slow. Do you prefer it over UFboot or aLRT? I personally vote for aLRT.

**Comment by duchene** [comment]
Update. We can now force non-monotypic alignments. Remember such analysis will get stuck when the internal branch length is very short or 0.

I think we are ready to run this on a few scenarios, but I do suggest we change to UFboot or aLRT branch supports.

**Comment by roblanf** [comment]
Awesome! Closing this issue. Let's open another one for the bootstrap question. But for now my feeling is that we just see how slow it is before we choose something faster. I think we have the compute to not worry about it, but let's see.
